env: local
host:
  address: ":8090"
database:
  write: "mysql_user:mysql_password@tcp(127.0.0.1:3306)/sunmoris_customer?timeout=30s&parseTime=true"
key:
  encrypt_key: "30caa5d889061a6f8820d7c723387b36cf62097c317f80de"
  jwt: "myjwtsecret"
api:
  timeout: 60
assets:
  url: "https://sunmorisemestaban.com/b6350926-8a8a-49ac-ab44-b52fd01fd2bb/"
