env: local
host:
  address: ":8097"
database:
  write: "root:password@tcp(127.0.0.1:3306)/libra_internal?timeout=30s&parseTime=true"
key:
  encrypt_key: "xxx"
  jwt: "xxx"
  anonymous: "xxx"
api:
  timeout: 60
assets:
  common:
    max_file_size: 1
  base_url: "https://xxx/"
  upload_path: "somepath/"
  profile_pic:
    max_size: 1
    path: "usr/"
midtrans:
  timeout: 30
  merchant_id: "xxxx"
  client_key: "xxx"
  server_key: "xxx"
