version: "3"

services:
  adminer:
    image: adminer
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_USER: mysql_user
      ADMINER_DEFAULT_PASSWORD: mysql_password

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sunmoris_customer
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
