package constants

// BNI
var (
	ATMInstructionBNI             []string = []string{"Masukkan Kartu Anda.", "Pilih Bahasa.", "Masukkan PIN ATM Anda.", "Pilih `Menu Lainnya`.", "Pilih `Transfer`.", "Pilih Jenis rekening yang akan Anda gunakan (Contoh; `Dari Rekening Tabungan`).", "Pilih `Virtual Account Billing`.", "Masukkan nomor Virtual Account Anda (contoh: 8241002201150001).", "Tagihan yang harus dibayarkan akan muncul pada layar konfirmasi.", "Konfirmasi, apabila telah sesuai, lanjutkan transaksi.", "Transaksi Anda telah selesai."}
	InternetBankingInstructionBNI []string = []string{"Ketik alamat https://ibank.bni.co.id kemudian klik `Enter`.", "Masukkan User ID dan Password.", "Pilih menu `Transfer`.", "Pilih `Virtual Account Billing`.", "Kemudian masukan nomor Virtual Account Anda (contoh: 8241002201150001) yang hendak dibayarkan. Lalu pilih rekening debet yang akan digunakan. Kemudian tekan `lanjut`.", "Kemudin tagihan yang harus dibayarkan akan muncul pada layar konfirmasi.", "Masukkan Kode Otentikasi Token.", "Pembayaran Anda telah berhasil."}
	MobileBankingInstructionBNI   []string = []string{"Akses BNI Mobile Banking dari handphone kemudian masukkan user ID dan password.", "Pilih menu `Transfer`.", "Pilih menu `Virtual Account Billing` kemudian pilih rekening debet.", "Masukkan nomor Virtual Account Anda (contoh: 8241002201150001) pada menu `input baru`.", "Tagihan yang harus dibayarkan akan muncul pada layar konfirmasi", "Konfirmasi transaksi dan masukkan Password Transaksi.", "Pembayaran Anda Telah Berhasil."}
	CODIntruction                 []string = []string{"Datang ke outlet kami di alamat sesuai dengan ke outlet yang anda pilih", "Ada beberapa cara pembayaran sistem COD yang bisa dilakukan.", "Pertama anda bisa bayar menggunakan uang cash / tunai.", "Kedua Anda juga bisa membayar menggunakan mesin EDC / Scan QRIS yang ada dioutlet kami.", "Terakhir anda dapat membayar dengan scan QRIS yang ada di halaman ini", "Jangan lupa simpan bukti transfer dan tunjukan bukti pemesanan kepada kasir untuk memverifikasi pembayaran anda."}
)
